### ISSUE TITLE
Why do some Virustotal.com scanners warn about UwTerminalX.exe?

### ISSUE THREAD

**Issue by schittli** [LairdCP/UwTerminalX#24]
Good morning,

Some Virustotal Scanner warns about UwTerminalX.exe: 
https://www.virustotal.com/gui/file/c4e7fe52eb0d19a7bf8b9d8bc1ddd9cae97b7f68c732c42df4bf8652192e5cca/detection

Do you know why they think that UwTerminalX.exe behaves badly?

Thanks a lot, kind regards,
Thomas

**Comment by thedjnK** [comment]
I would assume it is most likely caused by the use of UPX compression, generally some virus scanners will falsely detect UPX packed executables as viruses, see https://github.com/upx/upx/issues/337 for details. UPX is used to reduce the file size of executables e.g. the linux builds are reduced from about 50MB to about 20MB.

Individually "Razy" is the name of something generic and it gives no details, "Trojan.Malware.300983.susgen" gives no details, "BehavesLike.Win32.BadFile.tc" seems to be universal sign of a bad quality AV that requires manual exclusions added for every variant and build of software as per https://community.mcafee.com/t5/Web-Gateway/behaveslike-win32-downloader-wc-false-positive/td-p/478673, "Malicious" gives no details, "TrojanSpy.AutoIt.jh" seems to be suggesting the software has a scripting system known as autoit included from https://www.autoitscript.com/site/ which is both amusing and wrong, and "Artemis!DB1843160947" gives no results what so ever so I can't find details of that.
